# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LuciqSwiftUIDemo' do
  use_frameworks!

  # Pods for LuciqSwiftUIDemo
  pod 'Luciq', :podspec => '../Luciq.podspec'

end

target 'LuciqUIKitDemo' do
  use_frameworks!

  # Pods for LuciqUIKitDemo
  pod 'Luciq', :podspec => '../Luciq.podspec'

end
